## List all products
GET http://localhost:3333/products


## Create a product
###
POST http://localhost:3333/products/create
Content-Type: application/json

{
    "name": "Produto 3",
    "price": 30.1
}

## Buy a product
###
POST http://localhost:3333/products/08ac5470-13a4-45c5-9508-c20c21aa36c8/buy
Content-Type: application/json

{
    "amount": 100
}

## sell a product
###
POST http://localhost:3333/products/08ac5470-13a4-45c5-9508-c20c21aa36c8/sell
Content-Type: application/json

{
    "amount": 20
}